# Generated by Django 4.1.7 on 2023-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atapp', '0002_alter_book_email_alter_book_gender_alter_book_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='area',
        ),
        migrations.RemoveField(
            model_name='book',
            name='city',
        ),
        migrations.RemoveField(
            model_name='book',
            name='event',
        ),
        migrations.RemoveField(
            model_name='book',
            name='venues',
        ),
        migrations.AlterField(
            model_name='book',
            name='age',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
